### ISSUE TITLE
Update an old email address on TISLab website for Anita Walden

### ISSUE THREAD

**Issue by tursynay** [tis-lab/tislab.org#19]
I am submitting a few of these.

Please update the email address for Anita Walden from waldenan@ohsu.edu to anita.walden@sagebase.org. 

If one goes to tislab.org website and clicks on team (top right), then clicks on the icon for Anita, the email icon is set up for mailto:waldenan@ohsu.edu, needs to be changed to anita.walden@sagebase.org.

Here is the page: https://tislab.org/members/anita-walden.html where the incorrect email is listed.

**Comment by vincerubinetti** [comment]
Hi @tursynay , thanks for bringing up these issues. The [template](https://github.com/greenelab/lab-website-template) that this website is based on is meant to be easy to edit by technical and non-technical folks alike. Tislab folks themselves should be making changes like this. The Greenelab website is built on the template too, and all the lab members there make their own edits. I'll assign this to the appropriate parties instead of myself. People can look at [the documentation here](https://github.com/greenelab/lab-website-template/wiki) if they need to. I'm here to support more fundamental issues that may arise, like limitations with the template or documentation improvements.
