### ISSUE TITLE
Remove or Archive Liz Etherington from the teams page

### ISSUE THREAD

**Issue by tursynay** [tis-lab/tislab.org#45]
We still list Liz on this page: https://tislab.org/team/

**Comment by nicolevasilevsky** [comment]
@tursynay I realized I don't know how to do this. Can we create some documentation on how to add and remove members? Should I simply just delete her page from here: https://github.com/tis-lab/tislab.org/tree/main/_members?

**Comment by tursynay** [comment]
@nicolevasilevsky , I am not sure how to do it either, maybe @vincerubinetti can give us couple of pointers that we can use for documentation.

**Comment by nicolevasilevsky** [comment]
Thanks!
It looks like other past members have been deleted but I feel like we had them marked as alumni previously, so I don't want to delete anyone, in case we want to retain the provenance.

**Comment by vincerubinetti** [comment]
You can delete her member markdown file in `_members`, yes. But if you just want her to not show up on `/teams`, you could just add `tier: alumni` at the top of her file. 

For why this would work, see the `list.html` lines in the `/teams` file:

https://raw.githubusercontent.com/tis-lab/tislab.org/main/team/index.md

Note the filters. First we list all the members that have `tier` set to `first`, then `second`, then finally any team members that have no `tier` field set at all. Setting `tier` to `alumni`, or in fact any other value, will not be captured in any of those lists.

You also may wish to reorganize this to your liking. The tiers were just something I did to make sure Melissa etc were listed first rather than alphabetically. You can attach any fields you want to members, and you can filter by any field in any way in the `list.html` component.

Another note: a page would still be generated for Elizabeth at https://tislab.org/members/elizabeth-etherington.html , but it just wouldn't be linked to from the `/team` page. Someone would have to know the link already.

---

Please remember that the TISLab website is made from the Lab Website Template, which has very detailed documentation here:

https://github.com/greenelab/lab-website-template/wiki

**Comment by nicolevasilevsky** [comment]
Thanks @vincerubinetti! I didn't realize there was documentation on the greenelab repo, this is great. I will add this link on our ReadMe so we can easily reference it.
Thanks for your help.

**Comment by vincerubinetti** [comment]
Also, I wouldn't be hesitant to just completely delete her file? This is git/github, after all. One of its purposes is to track changes to code and be able to revert to old versions when needed. Her file will always be there in the commit history...

**Comment by nicolevasilevsky** [comment]
Good point @vincerubinetti, I will just delete her file. Thanks for your help!
